<?php

namespace AppBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllAnnonce(){
		$dql = "SELECT a 
				FROM AppBundle:Annonce a
				ORDER by a.categorie";
		$query = $this->_em->createQuery($dql);
		return $query->getResult();
	}
}
