annonce_categorie_index:
    path:     /
    defaults: { _controller: "AppBundle:Categorie:index" }
    methods:  GET

annonce_categorie_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Categorie:show" }
    methods:  GET

annonce_categorie_new:
    path:     /new
    defaults: { _controller: "AppBundle:Categorie:new" }
    methods:  [GET, POST]

annonce_categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Categorie:edit" }
    methods:  [GET, POST]

annonce_categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Categorie:deleteElement" }
    methods:  [GET, POST]
