<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNbbhcvk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNbbhcvk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNbbhcvk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNbbhcvk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNbbhcvk\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nbbhcvk',
    'container.build_id' => 'e65229f9',
    'container.build_time' => 1534367522,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNbbhcvk');
